# Welcome to Nubia Jekyll Theme!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

theme_version: 1.0.4

# Site settings
title:              Media Sejenak
logo:               https://www.mediasejenak.xyz/mslogo.png
description:        Thoughts, Stories and Ideas
baseurl:            '' # The subpath of your site, e.g. /blog
url:                'https://www.mediasejenak.xyz' # The base hostname & protocol for your site
twitter:            https://twitter.com/mediasejenak
facebook:           https://www.facebook.com/mediasejenak
instagram:          https://www.instagram.com/mediasejenak
timezone:           Asia/Jakarta

permalink: /:title

collections:
  amp:
    output: true
    permalink: /amp/:title/
  artikel:
    output: true
  news:
    output: true

markdown:  kramdown
paginate:  11

gems:
  - jekyll-paginate
  - jekyll/tagging
  - jekyll-tagging-related_posts
  - jekyll-redirect-from

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  ilham:
    name:     Ilham Maulana
    gravatar: https://www.mediasejenak.xyz/apple-icon-180x180.png
    email:    ilhammp1213@gmail.com
    twitter:  https://twitter.com/impwriters
